stages:
 - build
 - push
 - release

build_image:
  image: docker:latest
  services:
  - docker:dind
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/bencollier/cobol-api .
    - docker push registry.gitlab.com/bencollier/cobol-api:latest
    
push_to_heroku:
  image: docker:latest
  stage: push
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker pull registry.gitlab.com/bencollier/cobol-api:latest
    - docker login --username=_ --password=bd453113-7aed-4758-b613-bd07d98bd587 registry.heroku.com
    - docker tag registry.gitlab.com/bencollier/cobol-api:latest registry.heroku.com/cobol-api/web:latest
    - docker push registry.heroku.com/cobol-api/web:latest

deploy_to_heroku:
  image: node:latest
  stage: release
  services:
  - docker:dind
  script:
    - npm install -g heroku
    - heroku container:release web --app cobol-api