stages: 
    - package
    - push
    - deploy
 
.extendjob:  
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t registry.gitlab.com/<your-gitlab-username>/<your-docker-image-name> .
    - docker push registry.gitlab.com/<your-gitlab-username>/<your-docker-image-name>:latest
 
build_image:
  image: docker:latest
  services:
  - docker:dind
  stage: package
  extends: .extendjob  
 
 
push_to_heroku:
  image: docker:latest
  stage: push
  services:
  - docker:dind
  extends: .extendjob
  script:
    # This is for gitlab
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker pull  registry.gitlab.com/<your-gitlab-username>/<your-docker-image-name>:latest
    # This is for heroku
    - docker login --username=_  --password=<heroku-auth-token> registry.heroku.com
    - docker tag registry.gitlab.com/<your-gitlab-username>/<your-docker-image-name>:latest registry.heroku.com/aqueous-falls-31318/web:latest
    - docker push registry.heroku.com/<your-heroku-app-name>/web:latest
 
 
deploy_to_heroku:
  image: node:latest
  stage: deploy
  services:
  - docker:dind
  extends: .extendjob
  script:
    - npm install -g heroku
    - heroku container:release web --app <your-heroku-app-name>